# .github/actions/jfrog-ip-manager/action.yml
name: 'JFrog IP Manager'
description: 'Manage JFrog Artifactory IP allowlist'
inputs:
  action:
    description: 'Action to perform: add or remove'
    required: true
  jfrog-url:
    description: 'JFrog URL'
    required: true
  jfrog-token:
    description: 'JFrog access token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Get Runner IP
      id: ip
      shell: bash
      run: |
        IP=$(curl -s https://api.ipify.org)
        echo "ip=$IP" >> $GITHUB_OUTPUT
        
    - name: Manage IP Allowlist
      shell: bash
      run: |
        if [ "${{ inputs.action }}" = "add" ]; then
          echo "Adding IP ${{ steps.ip.outputs.ip }} to allowlist"
          # Add IP logic here
        else
          echo "Removing IP ${{ steps.ip.outputs.ip }} from allowlist"
          # Remove IP logic here
        fi