name: Main CI/CD Pipeline

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

env:
  BUILD_VERSION: ${{ github.sha }}
  BUILD_NUMBER: ${{ github.run_number }}

jobs:
  # Stage 1: Code Quality (runs on all events)
  code-quality:
    uses: ./.github/workflows/code-quality.yml
    secrets: inherit
    
  # Stage 2: Build Applications (runs on all events)
  build-apps:
    needs: code-quality
    uses: ./.github/workflows/build-apps.yml
    secrets: inherit
    
  # Stage 3: Build Docker Images (runs on all events)
  build-docker:
    needs: build-apps
    uses: ./.github/workflows/build-docker.yml
    secrets: inherit
    with:
      build-version: ${{ needs.build-apps.outputs.build-version }}
      
  # Stage 4: Publish Artifacts (only on push to development)
  publish-artifacts:
    if: github.event_name == 'push' && github.ref == 'refs/heads/development'
    needs: [build-apps, build-docker]
    uses: ./.github/workflows/publish-artifacts.yml
    secrets: inherit
    with:
      build-version: ${{ needs.build-apps.outputs.build-version }}
      
  # Stage 5: Deploy (only on push to development)
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/development'
    needs: [build-apps, publish-artifacts]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      build-version: ${{ needs.build-apps.outputs.build-version }}
      environment: 'dev'
      
  # Summary Job
  pipeline-summary:
    name: Pipeline Summary
    runs-on: ubuntu-latest
    needs: [code-quality, build-apps, build-docker, publish-artifacts, deploy]
    if: always()
    
    steps:
      - name: Pipeline Summary
        run: |
          echo "## Pipeline Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Build Version:** ${{ env.BUILD_VERSION }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Build Number:** ${{ env.BUILD_NUMBER }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Code Quality:** ${{ needs.code-quality.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Build Apps:** ${{ needs.build-apps.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Build Docker:** ${{ needs.build-docker.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Publish Artifacts:** ${{ needs.publish-artifacts.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Deploy:** ${{ needs.deploy.result }}" >> $GITHUB_STEP_SUMMARY 